name: Release

on:
  push:
    tags:
      - 'v*'

env:
  JAVA_VERSION: 17

jobs:
  release:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build release artifacts
        run: mvn -B -ntp clean package

      - name: Collect jars for release
        run: |
          mkdir -p release
          find . -path "*/target/*.jar" ! -name "original-*.jar" -exec cp {} release/ \;

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-bundles
          path: release

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true
